"""empty message

Revision ID: 9f25ec8b06da
Revises: 0763d677d453
Create Date: 2025-04-02 17:09:45.664950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f25ec8b06da'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributes',
    sa.Column('id_attribute', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_attribute')
    )
    op.create_table('category',
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id_category')
    )
    op.create_table('suppliers',
    sa.Column('id_supplier', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id_supplier')
    )
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('expired_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('staff_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('inventories',
    sa.Column('id_inventory', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cif', sa.String(length=10), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_inventory')
    )
    op.create_table('orders',
    sa.Column('id_order', sa.Integer(), nullable=False),
    sa.Column('inventories_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('received_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['inventories_id'], ['inventories.id_inventory'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id_supplier'], ),
    sa.PrimaryKeyConstraint('id_order')
    )
    op.create_table('products',
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('inventories_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id_category'], ),
    sa.ForeignKeyConstraint(['inventories_id'], ['inventories.id_inventory'], ),
    sa.PrimaryKeyConstraint('id_product')
    )
    op.create_table('user_inventory',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('inventories_id', sa.Integer(), nullable=False),
    sa.Column('permissions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inventories_id'], ['inventories.id_inventory'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('users_id', 'inventories_id')
    )
    op.create_table('detailedOrders',
    sa.Column('id_detail', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id_order'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id_product'], ),
    sa.PrimaryKeyConstraint('id_detail')
    )
    op.create_table('product_attributes',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id_attribute'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id_product'], ),
    sa.PrimaryKeyConstraint('product_id', 'attribute_id')
    )
    op.create_table('transactions',
    sa.Column('id_transaction', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('inventories_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['inventories_id'], ['inventories.id_inventory'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id_product'], ),
    sa.PrimaryKeyConstraint('id_transaction')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('transactions')
    op.drop_table('product_attributes')
    op.drop_table('detailedOrders')
    op.drop_table('user_inventory')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('inventories')
    op.drop_table('users')
    op.drop_table('suppliers')
    op.drop_table('category')
    op.drop_table('attributes')
    # ### end Alembic commands ###
